name: Run the Service Tests

on:
  workflow_dispatch:

jobs:
  execute:
    name: Run the service tests
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:

      - name: Chekout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install docker compose
        run: |
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Create docker composer environment file
        working-directory: servicetest
        run: | 
          echo "DOCKERHUB_USERNAME=${{vars.DOCKERHUB_USERNAME}}" >> .env
          echo "BRANCH_NAME=${{github.ref_name}}" >> .env
          cat .env          

      - name: Start the otel container
        working-directory: servicetest
        run: |
          docker-compose up -d otel
          sleep 10
          
      - name: Start the otel container
        working-directory: servicetest
        run: |
          docker-compose up -d chameleon
          sleep 10

          - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '23'
  
      - name: Download the standalone karate jar
        run: |
          wget -O /opt/karate.jar https://github.com/karatelabs/karate/releases/download/v1.5.1/karate-1.5.1.jar
  
      - name: Execute the SITs using karate
        working-directory: it/karate
        run: |
          java -jar /opt/karate.jar -h
              
      - name: Greetings log
        run: |
          docker container logs servicetest-chameleon-1
          sleep 10
  
      - name: Otel log
        run: |
          docker container logs servicetest-otel-1
          sleep 10
    
      - name: Stop and remove the containers   
        if: always()
        working-directory: servicetest
        run: |
          docker-compose down     
  