name: Run the Service Tests

on:
  workflow_dispatch:

jobs:
  execute:
    name: Execute Tests
    runs-on: ubuntu-24.04
    steps:

      - name: Get the application artifact version
        id: versions
        uses: keeonline/gh-actions/actions/artifact-version@v0.0.5

      # - name: Install docker compose
      #   run: |
      #     curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      #     chmod +x /usr/local/bin/docker-compose
      #     docker-compose --version

      - name: Set up docker compose
        uses: docker/setup-compose-action@v1.2.0

      - name: Create docker compose environment file
        working-directory: servicetest
        run: | 
          if [ "${{github.ref_type}}" == "branch" ]
          then
            echo "VERSION=${{steps.versions.outputs.branch}}" >> .env
          else
            echo "VERSION=${{steps.versions.outputs.release}}" >> .env
          fi
          cat .env          

      - name: Start the chameleon container
        working-directory: servicetest
        run: |
          docker-compose up -d
          sleep 10

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
  
      - name: Download the standalone karate jar
        run: |
          wget -O /opt/karate.jar https://github.com/karatelabs/karate/releases/download/v1.5.1/karate-1.5.1.jar
  
      - name: Execute the service tests using karate
        working-directory: servicetest/karate
        run: |
          java -jar /opt/karate.jar .
              
      - name: Upload service test reports
        uses: actions/upload-artifact@v4
        with:
          name: Service Test Reports
          path: servicetest/karate/target/karate-reports
  
      - name: Stop and remove containers   
        if: always()
        working-directory: servicetest
        run: |
          docker-compose down     
  